name: Maui Manager Deb

on:
  workflow_dispatch:
    inputs:
      mauimanBranch:
        description: 'Maui Manager Branch'
        required: true
        type: string
      packageCloudRepo:
        description: 'Package Cloud Repo'
        required: true
        default: 'testing'
        type: choice
        options:
        - testing
      packageVersion:
        description: 'Package Version'
        required: true
        type: string

jobs:
  build-deb:
    runs-on: ubuntu-22.04

    container:
      image: ubuntu:jammy
      env:
        DEBIAN_FRONTEND: noninteractive
        PACKAGECLOUD_TOKEN: ${{ secrets.PACKAGECLOUD_TOKEN }}

    steps:
      - name: Install basic packages
        run: apt-get update -q && apt-get -qy install sudo && apt-get -qy install curl wget gnupg python3-pip patchelf build-essential ruby-full

      - name: Install package cloud
        run: gem install package_cloud

      - name: Add required repo list
        run: |
          sudo touch /etc/apt/sources.list.d/kubuntu-ppa.list
          echo "deb https://ppa.launchpadcontent.net/kubuntu-ppa/backports/ubuntu jammy main" | sudo tee -a /etc/apt/sources.list.d/kubuntu-ppa.list
          curl 'http://keyserver.ubuntu.com/pks/lookup?op=get&search=0xE4DFEC907DEDA4B8A670E8042836CB0A8AC93F7A' | sudo apt-key add -

      - uses: actions/checkout@v2
      - name: Install build dependencies
        run: ./scripts/install-build-deps.sh

      - name: Generate deb
        run: ./scripts/build-deb.sh
        env:
          PACKAGE_VERSION: ${{ inputs.packageVersion }}
          MAUIMAN_BRANCH: ${{ inputs.mauimanBranch }}

      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v3
        with:
          name: deb-package
          path: ./build/*.deb
          retention-days: 1
      
      - name: Upload package to Package Cloud
        run: package_cloud push nitrux/${{ inputs.packageCloudRepo }}/debian/trixie ./build/*.deb